<?php

return [
    'BACO' => [
        'ALAG',
        'BANGKATAN',
        'BARAS',
        'BAYANAN',
        'BURBULI',
        'CATWIRAN I',
        'CATWIRAN II',
        'DULANGAN I',
        'DULANGAN II',
        'LANTUYANG',
        'LUMANG BAYAN',
        'MALAPAD',
        'MANGANGAN I',
        'MANGANGAN II',
        'MAYABIG',
        'PAMBISAN',
        'POBLACION',
        'PULANG-TUBIG',
        'PUTICAN-CABULO',
        'SAN ANDRES',
        'SAN IGNACIO',
        'SANTA CRUZ',
        'SANTA ROSA I',
        'SANTA ROSA II',
        'TABON-TABON',
        'TAGUMPAY',
        'WATER',
    ],
    'BANSUD' => [
        'ALCADESMA',
        'BATO',
        'CONRAZON',
        'MALO',
        'MANIHALA',
        'PAG-ASA',
        'POBLACION',
        'PROPER BANSUD',
        'PROPER TIGUISAN',
        'ROSACARA',
        'SALCEDO',
        'SUMAGUI',
        'VILLA PAG-ASA',
    ],
    'BONGABONG' => [
        'ANILAO',
        'APLAYA',
        'BAGUMBAYAN I',
        'BAGUMBAYAN II',
        'BATANGAN',
        'BUKAL',
        'CAMANTIGUE',
        'CARMUNDO',
        'CAWAYAN',
        'DAYHAGAN',
        'FORMON',
        'HAGAN',
        'HAGUPIT',
        'IPIL',
        'KALIGTASAN',
        'LABASAN',
        'LABONAN',
        'LIBERTAD',
        'LISAP',
        'LUNA',
        'MALITBOG',
        'MAPANG',
        'MASAGUISI',
        'MINA DE ORO',
        'MORENTE',
        'OGBOT',
        'ORCONUMA',
        'POBLACION',
        'POLUSAHI',
        'SAGANA',
        'SAN ISIDRO',
        'SAN JOSE',
        'SAN JUAN',
        'SANTA CRUZ',
        'SIGANGE',
        'TAWAS',
    ],
    'BULALACAO' => [
        'BAGONG SIKAT',
        'BALATASAN',
        'BENLI',
        'CABUGAO',
        'CAMBUNANG',
        'CAMPAASAN',
        'MAASIN',
        'MAUJAO',
        'MILAGROSA',
        'NASUKOB',
        'POBLACION',
        'SAN FRANCISCO',
        'SAN ISIDRO',
        'SAN JUAN',
        'SAN ROQUE',
    ],
    'CALAPAN' => [
        'BALINGAYAN',
        'BALITE',
        'BARUYAN',
        'BATINO',
        'BAYANAN I',
        'BAYANAN II',
        'BIGA',
        'BONTOC',
        'BUCAYAO',
        'BUHUAN',
        'BULUSAN',
        'CALERO',
        'CAMANSHAN',
        'CAMILMIL',
        'CANUBING I',
        'CANUBING II',
        'COMUNAL',
        'GUINOBATAN',
        'GULOD',
        'GUTAD',
        'IBABA EAST',
        'IBABA WEST',
        'ILAYA',
        'LALUD',
        'LAZARETO',
        'LIBIS',
        'LUMANG BAYAN',
        'MAHAL NA PANGALAN',
        'MAIDLANG',
        'MALAD',
        'MALAMIG',
        'MANAGPI',
        'MASIPIT',
        'NAG-IBA I',
        'NAG-IBA II',
        'NAVOTAS',
        'PACHOCA',
        'PALHI',
        'PANGGALAAN',
        'PARANG',
        'PATAS',
        'PERSONAS',
        'PUTINGTUBIG',
        'SALONG',
        'SAN ANTONIO',
        'SAN VICENTE CENTRAL',
        'SAN VICENTE EAST',
        'SAN VICENTE NORTH',
        'SAN VICENTE SOUTH',
        'SAN VICENTE WEST',
        'SANTA CRUZ',
        'SANTA ISABEL',
        'SANTA MARIA VILLAGE',
        'SANTA RITA',
        'SANTO NIÑO',
        'SAPUL',
        'SILONAY',
        'SUQUI',
        'TAWAGAN',
        'TAWIRAN',
        'TIBAG',
        'WAWA',
    ],
    'GLORIA' => [
        'AGOS',
        'AGSALIN',
        'ALMA VILLA',
        'ANDRES BONIFACIO',
        'BALETE',
        'BANUS',
        'BANUTAN',
        'BULAKLAKAN',
        'BUONG LUPA',
        'GAUDENCIO ANTONINO',
        'GUIMBONAN',
        'KAWIT',
        'LUCIO LAUREL',
        'MACARIO ADRIATICO',
        'MALAMIG',
        'MALAYONG',
        'MALIGAYA',
        'MALUBAY',
        'MANGUYANG',
        'MARAGOOC',
        'MIRAYAN',
        'NARRA',
        'PAPANDUNGIN',
        'SAN ANTONIO',
        'SANTA MARIA',
        'SANTA THERESA',
        'TAMBONG',
    ],
    'MANSALAY' => [
        'B. DEL MUNDO',
        'BALUGO',
        'BONBON',
        'BUDBURAN',
        'CABALWA',
        'DON PEDRO',
        'MALIWANAG',
        'MANAUL',
        'PANAYTAYAN',
        'POBLACION',
        'ROMA',
        'SANTA BRIGIDA',
        'SANTA MARIA',
        'SANTA TERESITA',
        'VILLA CELESTIAL',
        'WASIG',
        'WAYGAN',
    ],
    'NAUJAN' => [
        'ADRIALLUNA',
        'ANDRES ILAGAN',
        'ANTIPOLO',
        'APITONG',
        'ARANGIN',
        'AURORA',
        'BACUNGAN',
        'BAGONG BUHAY',
        'BALITE',
        'BANCURO',
        'BANUTON',
        'BARCENAGA',
        'BAYANI',
        'BUHANGIN',
        'CABURO',
        'CONCEPCION',
        'DAO',
        'DEL PILAR',
        'ESTRELLA',
        'EVANGELISTA',
        'GAMAO',
        'GENERAL ESCO',
        'HERRERA',
        'INARAWAN',
        'KALINISAN',
        'LAGUNA',
        'MABINI',
        'MAGTIBAY',
        'MAHABANG PARANG',
        'MALAYA',
        'MALINAO',
        'MALVAR',
        'MASAGANA',
        'MASAGUING',
        'MELGAR A',
        'MELGAR B',
        'METOLZA',
        'MONTELAGO',
        'MONTEMAYOR',
        'MOTODERAZO',
        'MULAWIN',
        'NAG-IBA I',
        'NAG-IBA II',
        'PAGKAKAISA',
        'PAITAN',
        'PANIQUIAN',
        'PINAGSABANGAN I',
        'PINAGSABANGAN II',
        'PIÑAHAN',
        'POBLACION I',
        'POBLACION II',
        'POBLACION III',
        'SAMPAGUITA',
        'SAN AGUSTIN I',
        'SAN AGUSTIN II',
        'SAN ANDRES',
        'SAN ANTONIO',
        'SAN CARLOS',
        'SAN ISIDRO',
        'SAN JOSE',
        'SAN LUIS',
        'SAN NICOLAS',
        'SAN PEDRO',
        'SANTA CRUZ',
        'SANTA ISABEL',
        'SANTA MARIA',
        'SANTIAGO',
        'SANTO NIÑO',
        'TAGUMPAY',
        'TIGKAN',
    ],
];
